#!/bin/bash

file=TicTacToe.java

if [ ! -f "$file" ]; then
    echo -e "Error: File '$file' not found.\nTest failed."
    exit 1
fi

num_right=0
total=0
line="________________________________________________________________________"
compiler=
interpreter=
language=
if [ "${file##*.}" = "py" ]; then
    if [ ! -z "$PYTHON_PATH" ]; then
        interpreter=$(which python.exe)
    else
        interpreter=$(which python3.2)
    fi
    command="$interpreter $file"
    echo -e "Testing $file\n"
elif [ "${file##*.}" = "java" ]; then
    language="java"
    command="java ${file%.java}"
    echo -n "Compiling $file..."
    javac $file
    echo -e "done\n"
fi

run_test() {
    (( ++total ))
    echo -n "Running test $total..."
    expected=$2
    received=$( echo -e $1 | $command 2>&1 | tr -d '\r' )
    if [ "$expected" = "$received" ]; then
        echo "success"
        (( ++num_right ))
    else
        echo -e "failure\n\nExpected$line\n$expected\nReceived$line\n$received\n"
    fi
}

run_test "1\n1\n2\n1\n1\n2\n2\n2\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n1\n1\n2\n2\n2\n3\n3\n2\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O | O |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"Player O wins."
run_test "3\n1\n2\n1\n3\n2\n2\n2\n3\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n1\n2\n2\n1\n2\n2\n3\n1" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n1\n2\n2\n1\n2\n2\n3\n3\n3\n2" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"Player O wins."
run_test "1\n3\n1\n2\n2\n3\n2\n2\n3\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   | O | X |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n1\n3\n2\n2\n2\n3\n3\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   | O |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   | O |"$'\n'"-------------"$'\n'"|   | X |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   | O |"$'\n'"-------------"$'\n'"|   | X | O |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   | O |"$'\n'"-------------"$'\n'"|   | X | O |"$'\n'"-------------"$'\n'"|   |   | X |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n2\n1\n2\n1\n3\n2\n1\n3\n1" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"|   | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"|   | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| X | O |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"Player O wins."
run_test "2\n2\n1\n1\n1\n3\n3\n1\n2\n1\n2\n3\n3\n2\n1\n2\n3\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   | X |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   | X |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| O |   | X |"$'\n'"-------------"$'\n'"|   | X |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| O |   | X |"$'\n'"-------------"$'\n'"|   | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| O |   | X |"$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| O |   | X |"$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| O |   | X |"$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| O | X |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| O | O | X |"$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| O | X |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| O | O | X |"$'\n'"-------------"$'\n'"| X | X | O |"$'\n'"-------------"$'\n'"| O | X | X |"$'\n'"-------------"$'\n'"Tie."
run_test "1\n1\n2\n1\n1\n2\n2\n2\n1\n1\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: Error: Position already taken."$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n1\n1\n2\n2\n2\n-1\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Error: Invalid row -1 received."$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n1\n1\n2\n2\n2\n1\n-1\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: Error: Invalid column -1 received."$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n1\n1\n2\n2\n2\nx\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Error: Invalid row 'x' received."$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."
run_test "1\n1\n2\n1\n1\n2\n2\n2\n1\nx\n1\n3" "-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X |   |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O |   |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player O: Enter a column (1..3) for player O: "$'\n'"-------------"$'\n'"| X | X |   |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: Error: Invalid column 'x' received."$'\n'"Enter a row (1..3) for player X: Enter a column (1..3) for player X: "$'\n'"-------------"$'\n'"| X | X | X |"$'\n'"-------------"$'\n'"| O | O |   |"$'\n'"-------------"$'\n'"|   |   |   |"$'\n'"-------------"$'\n'"Player X wins."

echo -e "\nTotal tests run: $total"
echo -e "Number correct : $num_right"
echo -n "Percent correct: "
echo "scale=2; 100 * $num_right / $total" | bc

if [ "$language" = "java" ]; then
   echo -e -n "\nRemoving class files..."
   rm -f *.class
   echo "done"
fi
